# Generated by Django 5.1.4 on 2025-03-26 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0003_remove_employee_firstname_remove_employee_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
